# Site Settings
title                    : "Workshop: MFE in React"
description              : "A workshop geared to help you create your first microfrontend using React and Webpack"
avatar: /docs/icon.png
logourl: /assets/img/dc_logo.png
theme: jekyll-theme-tactile