# Site Settings
title                    : "Workshop: MFE in React"
description              : "A workshop geared to help you create your first microfrontend using React and Webpack"
theme: jekyll-theme-tactile